modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="overload_sim"
version="0.1.0-alpha.3"
displayName="Overload Simulation"
description='''A data-driven AE2 Lightning Tech addon for lightning-grown simulation crystals and resource simulation.'''
[[mixins]]
config="overload_sim.mixins.json"
[[dependencies.overload_sim]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
[[dependencies.overload_sim]]
modId="neoforge"
type="required"
versionRange="[21.1.252,21.2)"
[[dependencies.overload_sim]]
modId="ae2"
type="required"
versionRange="[19.2.17]"
ordering="AFTER"
[[dependencies.overload_sim]]
modId="ae2lt"
type="required"
versionRange="[2.1.0]"
ordering="AFTER"
[[dependencies.overload_sim]]
modId="thunderbolt"
type="required"
versionRange="[2.0.0]"
ordering="AFTER"
[[dependencies.overload_sim]]
modId="guideme"
type="required"
versionRange="[21.1.19]"
ordering="AFTER"
